### ISSUE TITLE
bin/update crashes my kpiggybank

### ISSUE THREAD

**Issue by ozten** [mozilla/kpi-dashboard#13]
STR

1) cd server
2) ./bin/update

```
/home/ozten/kpi-dashboard/server/lib/data.js:23
        throw(e);
              ^
Error: socket hang up
    at createHangUpError (http.js:1264:15)
    at Socket.socketOnEnd [as onend] (http.js:1352:23)
    at TCP.onread (net.js:418:26)
```

An my kpiggybank console goes:

```
start /home/ozten/kpiggybank
> node lib/server.js

   info  - socket.io started
info: Using DB: couchdb
using db: bid_kpi
kpiggybank listening on port 3001 in development mode

http.js:715
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (http.js:715:11)
    at ServerResponse.OutgoingMessage.end (http.js:804:16)
    at /home/ozten/kpiggybank/lib/server.js:169:20
    at Request.cradle.Connection.request [as _callback] (/home/ozten/kpiggybank/node_modules/cradle/lib/cradle.js:198:20)
    at Request.init.self.callback (/home/ozten/kpiggybank/node_modules/request/main.js:119:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/home/ozten/kpiggybank/node_modules/request/main.js:521:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/home/ozten/kpiggybank/node_modules/request/main.js:483:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
```

**Comment by kparlante** [comment]
I think this has been fixed with the latest kpiggybank update, and #24.
